echo "my hostname is: $HOSTNAME "



myOS=$(sudo hostnamectl | grep Operating)
myuptime=$(uptime -p)
cpu_info=$(lscpu | grep "Model name" | awk -F: '{print $2}')

cpu_speed=$(grep "MHz" /proc/cpuinfo) 
ram_installed=$(free -h | grep "Mem" | awk -F: '{print $2}') 

disk_make=$(for disk in $(lsblk -dno NAME | grep -v '^loop'); do echo -n "Disk: /dev/$disk, Model: "; udevadm info --query=all --name=/dev/$disk | grep ID_MODEL= | awk - F= '{print $2}'; echo -n ", Size: "; lsblk -dno SIZE /dev/$disk; done)

video=$(lspci -nn | grep -i vga)
#####################################################
fqdn=$(hostname -f)
ip_add=$(nmcli device show ens37 | grep IP4.ADDRESS)
gateway=$(nmcli device show | grep 'IP4.GATEWAY' | awk '{print $2}' )
dns_server=$(nmcli | grep servers)
interface=$(sudo lshw -class network | grep -i "description:" -A 2)
network_addr=$(ip -o -4 addr show | awk '{print $4}' )

###########################################################

users_logged=$(who | awk '{print $1}')
avail_space=$(df -h | grep dev/sd)
process_no=$(ps -e | wc -l)
load_time=$(uptime | awk '{print $8, $9, $10}')
memory_allocation=$(free -h)
listening_port=$(ss -tuln | grep LISTEN | awk '{print $1, $3, $4, $5, $6}')
ufw_status=$(sudo ufw status | awk '{print $2}')







cat << ENDOFMYINPUT
System Report generated by $HOSTNAME , $DATE

system Information
################################
hostname: $HOSTNAME
Operatiing ayatem: $myOS
Uptime: $myuptime

Hardware Information

################################################

cpu: $cpu_info
Speed: $cpu_speed
Ram: $ram_installed
Disk: $disk_make
video card: $video

#############################################

Network Information
FQDN: $fqdn
Host Address: $ip_add
Gateway IP: $gateway
DNS Server: $dns_server
InterfaceName: $interface
IP Address: $network_addr


################################################

Users Logged In: $users_logged
Disk Space: $avail_space
Process Count: $process_no
Load Averages: $load_time
Memory Allocation: $memory_allocation
Listening Network Ports: $listening_port
UFW Rules: $ufw_status



ENDOFMYINPUT
